webtalk_init -webtalk_dir C:/Users/yando/Desktop/driver/FPGA/01_combinational_logic_example/04_xor_demo/xor_demo/xor_demo.sim/sim_1/behav/xsim/xsim.dir/tb_xor_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jun 20 11:47:18 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8cd85910-cdac-4f64-a325-cd5c037d9adf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9bd3f1e49581439fa9ad791388ef2ddb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6492_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3477011016 -regid "" -xml C:/Users/yando/Desktop/driver/FPGA/01_combinational_logic_example/04_xor_demo/xor_demo/xor_demo.sim/sim_1/behav/xsim/xsim.dir/tb_xor_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/yando/Desktop/driver/FPGA/01_combinational_logic_example/04_xor_demo/xor_demo/xor_demo.sim/sim_1/behav/xsim/xsim.dir/tb_xor_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/yando/Desktop/driver/FPGA/01_combinational_logic_example/04_xor_demo/xor_demo/xor_demo.sim/sim_1/behav/xsim/xsim.dir/tb_xor_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
